server:
  port: 8080
  database:
    driver: postgres
    host: localhost
    port: 5432
    user: postgres
    password: admin
    dbname: todo
    sslmode: disable
    sslrootcert:
    sslkey:
    sslcert: